# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "centos/7"

    config.vm.hostname = "admin.mazhr.dev"
    config.vm.network :private_network, ip: "10.0.0.1"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/development.yml"
        ansible.host_key_checking = false
        ansible.sudo = true
    end

    config.vm.provider "virtualbox" do |v|
        v.name = "admin.mazhr.dev"
        v.memory = 516
        v.customize ["modifyvm", :id, "--cpus", 2]
    end
end
