---
# This playbook deploys the whole application stack to STAGING-environment.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo
  vars_files:
    - config/development-config.yml
  roles:
    - common
    - webserver
    - appserver
#    - db-server
#    - memcached
    - vagrant
#    - db-migration
